name: Build and deploy ASP.Net Core app to Azure Web App - NexTechOmarMousa

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PUBLISH_OUTPUT: 'publish_output'  # Define a consistent output folder name

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build Backend/Backend.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Backend/Backend.csproj -c Release -o ${{env.PUBLISH_OUTPUT}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.PUBLISH_OUTPUT}}

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{env.PUBLISH_OUTPUT}}  # Download to same folder structure
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NexTechOmarMousa'
          slot-name: 'Production'
          package: ${{env.PUBLISH_OUTPUT}}  # Point to the published output
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_22DBB823175343EAB50C7703DF3A9CA4 }}
